UX: be specific if disko-install failed or succeeded (#847) UX: be specific if disko-install failed or succeeded
* Output success message to stdout

Co-authored-by: Jörg Thalheim <Mic92@users.noreply.github.com>

diff --git a/disko-install b/disko-install
--- a/disko-install
+++ b/disko-install
@@ -244,4 +244,10 @@ main() {
   nixos-install --no-channel-copy --no-root-password --system "$nixos_system" --root "$mountPoint"
 }
 
-main "$@"
+if main "$@"; then
+  echo "disko-install succeeded"
+  exit 0
+else
+  echo "disko-install failed" >&2
+  exit 1
+fi
